---
title: KSP Part Catalog
timezone: Europe/Amsterdam
collections:
  client_collection:
    title: Pagina's inhoud
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  parts_min:
    title: Parts
    output: true
volledige-titel: KSP Part Catalog
tags: KSP Part Catalog
# phone: 06-12345678
# email: effie@testmail.com
description: KSP Part Catalog
baseurl: 
url: 
# facebook_username: Effie
# twitter_username: Effie
markdown: kramdown
theme: minima
plugins: 
author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Designer
  email: sem.postma@gmail.com
